### ISSUE TITLE
Add support for `roles`

### ISSUE THREAD

**Issue by Jandev** [nikneem/azure-functions-jwt-binding#23]
When working with [application roles (appRoles inside the Azure Active Directory Manifest)](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps) it would be great to do some validation on these claims also.

The payload looks like this:
```json
{
  "aud": "[guid]",
  "iss": "https://sts.windows.net/[theTenant]/",
  "idp": "https://sts.windows.net/[theTenant]/",
  "oid": "some-guid-of-my-user-or-service",
  "roles": [
    "My",
    "Awesome",
    "Roles"
  ]
}
```

If this validation can't be added, or you don't think this is fitting for the binding, please provide the `roles` as a property in the `AuthorizeModel`, so we can do the validation by ourselves once the initial validation of the token is complete.

**Comment by nikneem** [comment]
That would be a good add-on. I think I'm going to add an additional optional param to the binding allowing you to validate roles. I was looking for a way to -instantly- validate the token without having to do any additional work (checks & validations) foe each and every request. So adding them to the returned model is a no-go in imho because this would require manual checks.

Thanks for thinking along @Jandev
