### ISSUE TITLE
FeatureRequest: 401 - UnauthorizedAccess

### ISSUE THREAD

**Issue by DavidHoffmann** [nikneem/azure-functions-jwt-binding#36]
Hi,

it would be nice if there is an unauthorized access that the request returns a "401 Unauthorized" and not a "500 Error".

Best regards,
  David

**Comment by nikneem** [comment]
Sent out a message to the functions team. This is not possible now. As expected, the binding runs outside the context of your function itself and can therefore not return a HTTP status code on its own. For now we're going to have to stick with the 500.

There is a huge amount of feature requests for adding middleware by the way, this would totally solve the problem. But until this is implemented, there's no possible way to archief this.

**Comment by jdearing-neudesic** [comment]
@nikneem what if there was a configuration option to not return 500 (I guess wrap everything into a try/catch to avoid refactoring) and then put an error response in the  AuthModel. Each function would need to do an if block to check for this, but it could be as simple as `if (auth.IsAuthenticated) { return auth.FailureResponse; }`

**Comment by nikneem** [comment]
I think the would be unwanted since users now have to forcibly add the if statement to each and every endpoint. Also will this introduce a major breaking change. We're waiting for the .NET 5 runtime to implement returning proper status codes because we're allowed to add pipeline validations. So that's a major advantage because A) JWT validation will probably work out of the box and B) we can handle exceptions and failing validations way better
