### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by nikneem** [nikneem/azure-functions-jwt-binding#8]
I'm missing unit tests. Need more confidence in the code...

**Comment by joaopgrassi** [comment]
Hey, I'd love to help with this. I submitted a draft PR #18 which for now contains only tests regarding the wire-up of the startup class (and the services required). 

What else you had in mind for this ticket? I see there's several unit tests for the "core" part `TokenValidatorService` which are great. The rest I'm not so sure benefits from unit testing. For example, the `JwtBinding`. I don't see much value in unit testing it since we would need to manually instantiate it and call `Initialize`.

What I think is more beneficial is to have some sort of integration test. We could have another project which contains a real azure function, install this binding and start the whole thing to see if all works. 

I have done ASP.NET Core integration tests quite a bit, but from a quick read it's a bit different with functions. We would need the runtime/host running, but I think it's not that bad. Would be similar to have a docker container running with a database. 

This post seems to be what is needed: https://medium.com/cheranga/testing-azure-functions-part-2-86e036785f59.

Let me know what are your thoughts :)

**Comment by nikneem** [comment]
I'm so sorry, this issue should have already been marked as solved as the tests are already in place. Your observation is spot on.

I don't think it makes sense to add integration tests to this project. The test would become too complicated compared to the value they deliver.

I do want to thank you for your interest in my project.

**Comment by joaopgrassi** [comment]
No prob, sounds good :). I will leave the other PR though as it's already there. You can either merge or just forget about it :).
